# Generated by Django 4.0.1 on 2022-03-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_alter_booking_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
